name: circles
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/icons/
    - assets/images/logo/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/fira_sans/FiraSans-ThinItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Thin.ttf
        - asset: assets/fonts/fira_sans/FiraSans-SemiBoldItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-SemiBold.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Regular.ttf
        - asset: assets/fonts/fira_sans/FiraSans-MediumItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Medium.ttf
        - asset: assets/fonts/fira_sans/FiraSans-LightItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Light.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Italic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-ExtraLightItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-ExtraLight.ttf
        - asset: assets/fonts/fira_sans/FiraSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-ExtraBold.ttf
        - asset: assets/fonts/fira_sans/FiraSans-BoldItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Bold.ttf
        - asset: assets/fonts/fira_sans/FiraSans-BlackItalic.ttf
        - asset: assets/fonts/fira_sans/FiraSans-Black.ttf

flutter_intl:
  enabled: true
